# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [2]:
cars1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")
cars2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")

print(cars1.head())
print(cars2.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN
1       1          buick skylark 320         NaN          NaN          NaN
2       1         plymouth satellite         NaN          NaN          NaN
3       1              amc rebel sst         NaN          NaN          NaN
4       1                ford torino         NaN          NaN          NaN

   Unnamed: 12  Unnamed: 13
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76
1  20.0          6           225        100    3651          17.7     76
2  18.0          6           250         78    3574          21.0     76
3  18.5          6           250        110    3645          16.2     76
4  17.5          6           258         95    3193          17.8     76

   origin                 car
0       3         honda civic
1       1      dodge aspen se
2       1   ford granada ghia
3       1  pontiac ventura sj
4       1       amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [3]:
cars1 = cars1.loc[:, "mpg":"car"]
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [4]:
print(cars1.shape)
print(cars2.shape)

(198, 9)
(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [5]:
cars = pd.concat([cars1, cars2], ignore_index=True)

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [6]:
nr_owners = np.random.randint(15000, high=73001, size=398, dtype='l')
nr_owners

array([32633, 27238, 50121, 40094, 44150, 26072, 52478, 24452, 39527,
       45563, 28632, 25851, 63209, 49426, 58329, 17881, 64935, 64540,
       27303, 54929, 62777, 62022, 56923, 40604, 59332, 38353, 59435,
       34499, 60334, 22190, 15774, 46676, 57975, 68412, 35676, 34139,
       40801, 30187, 41763, 28443, 36641, 34253, 21979, 26222, 60239,
       27862, 16857, 57837, 40157, 30232, 64170, 39261, 54491, 27805,
       29639, 16177, 29783, 18733, 51448, 48517, 59440, 36078, 35827,
       22196, 42037, 18722, 23283, 45955, 64678, 15703, 49910, 50550,
       71568, 17526, 32317, 29484, 48866, 19072, 69937, 53622, 54911,
       65799, 16029, 37948, 39119, 50020, 42595, 33213, 37654, 31722,
       25956, 26879, 26846, 57417, 56934, 40148, 24042, 58319, 57405,
       41318, 50341, 53542, 31683, 45212, 69546, 31656, 31402, 58429,
       51364, 64973, 70082, 38788, 56398, 63505, 72688, 53065, 41148,
       68484, 26835, 58024, 28218, 57588, 28389, 27111, 40131, 17641,
       33764, 53848, 19035, 60437, 38362, 36049, 22739, 72529, 40043,
       69089, 28571, 65345, 70258, 70092, 44453, 52320, 60406, 35842,
       24854, 72118, 30176, 72919, 67802, 59857, 55871, 16852, 16595,
       48455, 54994, 46778, 51285, 51056, 45356, 51113, 56896, 63279,
       62384, 37065, 71671, 22370, 33918, 23867, 51130, 67057, 68158,
       18437, 46462, 36487, 47893, 61012, 63148, 37434, 65626, 66008,
       62278, 39286, 57943, 16824, 50454, 45894, 33921, 67812, 69815,
       59388, 49580, 65939, 68210, 45342, 22735, 49851, 64695, 24810,
       64838, 66269, 33035, 36659, 20122, 66848, 35136, 31174, 15577,
       55263, 32479, 42588, 49832, 60629, 32569, 26888, 30899, 65710,
       15889, 28851, 50832, 15064, 27264, 69448, 36094, 60046, 59521,
       57663, 20508, 33891, 37986, 45496, 69385, 41942, 41027, 18020,
       49247, 55059, 64082, 68845, 61387, 22743, 20173, 56061, 68818,
       38565, 25733, 34440, 26082, 68677, 41263, 49433, 29081, 50119,
       50660, 71067, 38171, 36389, 63448, 71795, 48017, 72375, 44373,
       54670, 30006, 58370, 20487, 69691, 57392, 50357, 38192, 65928,
       58853, 58386, 39609, 35811, 35213, 44078, 34943, 22977, 26862,
       18332, 50777, 70264, 41362, 33472, 57861, 47081, 57290, 25158,
       16998, 32859, 59707, 18234, 15408, 18707, 19195, 46841, 45247,
       32743, 61796, 17739, 23308, 20479, 16718, 31055, 18216, 38038,
       45365, 29278, 54765, 68142, 45285, 54476, 58123, 42383, 21469,
       49037, 32396, 66643, 22676, 22028, 27420, 17318, 51612, 34953,
       67619, 23821, 67202, 34773, 21916, 56673, 40841, 29526, 19784,
       66937, 36041, 36940, 32519, 37153, 16259, 40257, 39361, 42272,
       72680, 44663, 26592, 58278, 71488, 41991, 21891, 44930, 34202,
       32306, 56863, 39367, 20829, 17269, 46854, 69401, 64945, 60071,
       16499, 19143, 20288, 62821, 26372, 31452, 41356, 34970, 65664,
       46229, 20271, 31866, 59911, 52044, 51388, 43659, 46367, 50545,
       20521, 69389, 59246, 68569, 56064, 41859, 60106, 15070, 21259,
       34172, 26164, 31375, 49400, 44308, 29562, 47071, 58339, 70590,
       60006, 50743], dtype=int32)

### Step 8. Add the column owners to cars

In [7]:
cars['owners'] = nr_owners
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,32633
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,27238
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,50121
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,40094
4,17.0,8,302,140,3449,10.5,70,1,ford torino,44150
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,47071
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,58339
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage,70590
396,28.0,4,120,79,2625,18.6,82,1,ford ranger,60006
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10,50743